name: to_do_list
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0-169.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  flutter_speed_dial: ^7.0.0
  go_router: ^12.1.3
  intl: ^0.19.0
  riverpod_annotation: ^2.3.3
  shared_preferences: ^2.2.2
  uuid: ^4.2.1

dev_dependencies:
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7

flutter:
  uses-material-design: true
