// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaSijdt1ga_A6-xmRtlMC3v2fQcLj3k0Q',
    appId: '1:445118523896:web:cf4549b85bcf9392310e0d',
    messagingSenderId: '445118523896',
    projectId: 'to-do-list-flutter-80eb1',
    authDomain: 'to-do-list-flutter-80eb1.firebaseapp.com',
    storageBucket: 'to-do-list-flutter-80eb1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbpsVjrhI5KWVbVFl-N-IibgeJ8zZGW4c',
    appId: '1:445118523896:android:75ad30d514c9b578310e0d',
    messagingSenderId: '445118523896',
    projectId: 'to-do-list-flutter-80eb1',
    storageBucket: 'to-do-list-flutter-80eb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0pYuHvIV4bMsV0aYgh6hREf55J_Jd3sI',
    appId: '1:445118523896:ios:e10297ffe555c189310e0d',
    messagingSenderId: '445118523896',
    projectId: 'to-do-list-flutter-80eb1',
    storageBucket: 'to-do-list-flutter-80eb1.appspot.com',
    iosBundleId: 'com.example.toDoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0pYuHvIV4bMsV0aYgh6hREf55J_Jd3sI',
    appId: '1:445118523896:ios:460537f5e9c8307f310e0d',
    messagingSenderId: '445118523896',
    projectId: 'to-do-list-flutter-80eb1',
    storageBucket: 'to-do-list-flutter-80eb1.appspot.com',
    iosBundleId: 'com.example.toDoList.RunnerTests',
  );
}
